# Generated by Django 5.2.17 on 2026-10-04 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('repo_path', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('canonical_setting', '设定系'), ('character', '人物'), ('timeline', '时间线'), ('event', '事件'), ('item', '物品'), ('location', '地点'), ('faction', '势力'), ('floating_tip', '游离设定')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', '有效'), ('archived', '归档')], default='active', max_length=20)),
                ('git_path', models.CharField(blank=True, default='', max_length=1000)),
                ('commit_hash', models.CharField(blank=True, default='', max_length=64)),
                ('sync_status', models.CharField(choices=[('pending', '待同步'), ('synced', '已同步'), ('failed', '同步失败')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.worldworkspace')),
            ],
            options={
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canvas_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('database_committed', '数据库已提交'), ('git_syncing', 'Git同步中'), ('synced', '已同步'), ('git_sync_failed', 'Git同步失败'), ('projection_sync_failed', '图谱同步失败')], default='pending', max_length=40)),
                ('entity_ids', models.JSONField(blank=True, default=list)),
                ('relation_ids', models.JSONField(blank=True, default=list)),
                ('commit_hash', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_jobs', to='core.worldworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('DERIVES_FROM', '衍生自'), ('BELONGS_TO', '归属于'), ('LINKED_TO', '关联到'), ('INFLUENCES', '影响'), ('CONFLICTS_WITH', '冲突于'), ('EVOLVES_TO', '演变为'), ('KNOWS', '认识'), ('LOCATED_AT', '位于'), ('OWNS', '拥有'), ('PARTICIPATES_IN', '参与'), ('PARENT_OF', '父级'), ('INHERITS_FROM', '继承自')], max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('weight', models.FloatField(default=1.0)),
                ('valid_from', models.BigIntegerField(blank=True, null=True)),
                ('valid_to', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='core.entity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='core.entity')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='core.worldworkspace')),
            ],
            options={
                'ordering': ['relation_type', 'created_at'],
                'indexes': [models.Index(fields=['workspace', 'source'], name='core_relati_workspa_dcd885_idx'), models.Index(fields=['workspace', 'target'], name='core_relati_workspa_7078ba_idx'), models.Index(fields=['workspace', 'relation_type'], name='core_relati_workspa_168364_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='relation_valid_range')],
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['workspace', 'type'], name='core_entity_workspa_d65931_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['workspace', 'status'], name='core_entity_workspa_7e206a_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['workspace', 'title'], name='core_entity_workspa_a475b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='commitjob',
            constraint=models.UniqueConstraint(fields=('workspace', 'idempotency_key'), name='workspace_idempotency_key'),
        ),
    ]
