# Generated by Django 5.2.17 on 2026-10-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitjob',
            name='actor',
            field=models.CharField(default='local-user', max_length=100),
        ),
        migrations.AddField(
            model_name='commitjob',
            name='export_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='commitjob',
            name='request_data',
            field=models.JSONField(default=dict),
        ),
    ]
