# Generated by Django 5.2.17 on 2026-10-04 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models



def create_main_branches(apps, schema_editor):
    Workspace = apps.get_model("core", "WorldWorkspace")
    Branch = apps.get_model("core", "WorldBranch")
    for workspace in Workspace.objects.all():
        Branch.objects.get_or_create(workspace=workspace, name="main", defaults={"status": "active"})

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commitjob_actor_commitjob_export_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('merged', 'Merged'), ('archived', 'Archived')], default='active', max_length=16)),
                ('base_snapshot', models.JSONField(blank=True, default=dict)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.worldworkspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='commitjob',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commit_jobs', to='core.worldbranch'),
        ),
        migrations.AddField(
            model_name='entity',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.worldbranch'),
        ),
        migrations.AddField(
            model_name='relation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='core.worldbranch'),
        ),
        migrations.RunPython(create_main_branches, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='worldbranch',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_branch_name'),
        ),
    ]
