# Generated by Django 5.2.17 on 2026-10-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_graphprojectionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldbranch',
            name='base_commit',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='worldbranch',
            name='git_ref',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
