# Generated by Django 5.2.17 on 2026-10-04 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_worldbranch_base_commit_worldbranch_git_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('epoch_label', models.CharField(blank=True, default='', max_length=160)),
                ('unit_name', models.CharField(default='tick', max_length=80)),
                ('units', models.JSONField(blank=True, default=list, help_text="Ordered display units, e.g. [{name: 'year', ticks: 360}]")),
                ('display_format', models.CharField(default='{value} {unit}', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_systems', to='core.worldworkspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_value', models.BigIntegerField()),
                ('end_value', models.BigIntegerField(blank=True, null=True)),
                ('sequence', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='core.worldbranch')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_occurrences', to='core.entity')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='core.entity')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='core.worldworkspace')),
                ('time_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.timesystem')),
            ],
            options={
                'ordering': ['start_value', 'sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterLifespan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_value', models.BigIntegerField(blank=True, null=True)),
                ('end_value', models.BigIntegerField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_lifespans', to='core.worldbranch')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifespans', to='core.entity')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_lifespans', to='core.worldworkspace')),
                ('time_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifespans', to='core.timesystem')),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='time_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations', to='core.timesystem'),
        ),
        migrations.CreateModel(
            name='TimelineParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_participations', to='core.entity')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.timelineentry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'entity'), name='unique_timeline_participant')],
            },
        ),
        migrations.AddConstraint(
            model_name='timesystem',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_time_system_name'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['workspace', 'time_system', 'start_value'], name='core_timeli_workspa_240812_idx'),
        ),
        migrations.AddConstraint(
            model_name='timelineentry',
            constraint=models.CheckConstraint(condition=models.Q(('end_value__isnull', True), ('end_value__gte', models.F('start_value')), _connector='OR'), name='timeline_entry_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='timelineentry',
            constraint=models.UniqueConstraint(fields=('timeline', 'event', 'time_system', 'branch'), name='unique_timeline_event_axis_branch'),
        ),
        migrations.AddConstraint(
            model_name='characterlifespan',
            constraint=models.CheckConstraint(condition=models.Q(('end_value__isnull', True), ('start_value__isnull', True), ('end_value__gte', models.F('start_value')), _connector='OR'), name='character_lifespan_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='characterlifespan',
            constraint=models.UniqueConstraint(fields=('character', 'time_system', 'branch'), name='unique_character_lifespan_axis_branch'),
        ),
    ]
