# Generated by Django 5.2.17 on 2026-10-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timesystem_timelineentry_characterlifespan_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='characterlifespan',
            name='unique_character_lifespan_axis_branch',
        ),
        migrations.RemoveConstraint(
            model_name='timelineentry',
            name='unique_timeline_event_axis_branch',
        ),
        migrations.AddConstraint(
            model_name='characterlifespan',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('character', 'time_system'), name='unique_character_lifespan_axis_main'),
        ),
        migrations.AddConstraint(
            model_name='characterlifespan',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('character', 'time_system', 'branch'), name='unique_character_lifespan_axis_branch'),
        ),
        migrations.AddConstraint(
            model_name='timelineentry',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('timeline', 'event', 'time_system'), name='unique_timeline_event_axis_main'),
        ),
        migrations.AddConstraint(
            model_name='timelineentry',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('timeline', 'event', 'time_system', 'branch'), name='unique_timeline_event_axis_branch'),
        ),
    ]
