# Generated by Django 5.2.17 on 2026-10-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_characterlifespan_unique_character_lifespan_axis_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterlifespan',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
