# Generated by Django 5.2.17 on 2026-10-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_characterlifespan_archived_timelineentry_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='base_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_overrides', to='core.entity'),
        ),
        migrations.AddField(
            model_name='relation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relation',
            name='base_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_overrides', to='core.relation'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['workspace', 'branch', 'base_entity'], name='core_entity_workspa_a3ded6_idx'),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['workspace', 'branch', 'base_relation'], name='core_relati_workspa_c0143d_idx'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(condition=models.Q(('base_entity__isnull', False), ('branch__isnull', False)), fields=('branch', 'base_entity'), name='unique_branch_base_entity_override'),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(condition=models.Q(('base_relation__isnull', False), ('branch__isnull', False)), fields=('branch', 'base_relation'), name='unique_branch_base_relation_override'),
        ),
    ]
