# Generated by Django 5.2.17 on 2026-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_commitjob_attempts_commitjob_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commitjob',
            index=models.Index(fields=['status', 'next_attempt_at', 'lease_until'], name='commit_outbox_ready_idx'),
        ),
        migrations.AddIndex(
            model_name='graphprojectionjob',
            index=models.Index(fields=['status', 'next_attempt_at', 'lease_until'], name='graph_outbox_ready_idx'),
        ),
    ]
