# Generated by Django 5.2.17 on 2026-10-04 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_commitjob_commit_outbox_ready_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSystemConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numerator', models.PositiveBigIntegerField(default=1)),
                ('denominator', models.PositiveBigIntegerField(default=1)),
                ('offset', models.BigIntegerField(default=0)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_conversions', to='core.timesystem')),
                ('target_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_conversions', to='core.timesystem')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_system_conversions', to='core.worldworkspace')),
            ],
            options={
                'ordering': ['source_system__name', 'target_system__name'],
                'indexes': [models.Index(fields=['workspace', 'source_system'], name='time_conv_source_idx'), models.Index(fields=['workspace', 'target_system'], name='time_conv_target_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_system', models.F('target_system')), _negated=True), name='time_conversion_distinct_systems'), models.CheckConstraint(condition=models.Q(('numerator__gt', 0), ('denominator__gt', 0)), name='time_conversion_positive_scale'), models.UniqueConstraint(fields=('workspace', 'source_system', 'target_system'), name='unique_time_conversion_route')],
            },
        ),
    ]
