# Generated by Django 5.2.17 on 2026-10-04 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(default='default', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(default='产婆式构建对话', max_length=200)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', '活跃'), ('archived', '归档')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_sessions', to='core.worldworkspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DialogueMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, default='', max_length=50)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='canvas.dialoguesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('user', '用户'), ('ai', 'AI')], default='ai', max_length=20)),
                ('entity_type', models.CharField(choices=[('canonical_setting', '设定系'), ('character', '人物'), ('timeline', '时间线'), ('event', '事件'), ('item', '物品'), ('location', '地点'), ('faction', '势力'), ('floating_tip', '游离设定')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('superseded', '已替代')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposals', to='core.entity')),
                ('dialogue_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_proposals', to='canvas.dialoguesession')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_proposals', to='canvas.dialoguemessage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_proposals', to='core.worldworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StagingCanvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='未命名暂存区', max_length=200)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('snapshot_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', '活跃'), ('archived', '归档'), ('committed', '已提交')], default='active', max_length=20)),
                ('last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to='core.worldworkspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RelationProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('DERIVES_FROM', '衍生自'), ('BELONGS_TO', '归属于'), ('LINKED_TO', '关联到'), ('INFLUENCES', '影响'), ('CONFLICTS_WITH', '冲突于'), ('EVOLVES_TO', '演变为'), ('KNOWS', '认识'), ('LOCATED_AT', '位于'), ('OWNS', '拥有'), ('PARTICIPATES_IN', '参与'), ('PARENT_OF', '父级'), ('INHERITS_FROM', '继承自')], max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已接受'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposal', to='core.relation')),
                ('source_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_relations', to='canvas.entityproposal')),
                ('target_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_relation_proposals', to='core.entity')),
                ('target_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_relation_proposals', to='canvas.entityproposal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_proposals', to='core.worldworkspace')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_proposals', to='canvas.stagingcanvas')),
            ],
            options={
                'ordering': ['-confidence', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='entityproposal',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_proposals', to='canvas.stagingcanvas'),
        ),
        migrations.AddField(
            model_name='dialoguesession',
            name='canvas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue_sessions', to='canvas.stagingcanvas'),
        ),
        migrations.CreateModel(
            name='CanvasRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='canvas.stagingcanvas')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='entityproposal',
            index=models.Index(fields=['canvas', 'status'], name='canvas_enti_canvas__ddb75e_idx'),
        ),
        migrations.AddConstraint(
            model_name='canvasrevision',
            constraint=models.UniqueConstraint(fields=('canvas', 'version'), name='canvas_revision_version'),
        ),
    ]
