# Generated by Django 5.2.17 on 2026-10-04 08:07

import django.db.models.deletion
from django.db import migrations, models



def assign_canvas_branches(apps, schema_editor):
    Canvas = apps.get_model("canvas", "StagingCanvas")
    Branch = apps.get_model("core", "WorldBranch")
    for canvas in Canvas.objects.select_related("workspace").all():
        branch, _ = Branch.objects.get_or_create(
            workspace_id=canvas.workspace_id,
            name=f"canvas-{str(canvas.id).replace('-', '')[:12]}",
            defaults={"status": "active"},
        )
        canvas.branch_id = branch.id
        canvas.save(update_fields=["branch"])

class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
        ('core', '0003_worldbranch_commitjob_branch_entity_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingcanvas',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canvases', to='core.worldbranch'),
        ),
        migrations.RunPython(assign_canvas_branches, migrations.RunPython.noop),
    ]
