# Generated by Django 5.2.17 on 2026-10-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_stagingcanvas_branch'),
        ('core', '0007_remove_characterlifespan_unique_character_lifespan_axis_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationproposal',
            name='time_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_proposals', to='core.timesystem'),
        ),
        migrations.AddField(
            model_name='relationproposal',
            name='valid_from',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationproposal',
            name='valid_to',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
