# Generated by Django 5.2.17 on 2026-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_relationproposal_time_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasrevision',
            name='sync_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stagingcanvas',
            name='sync_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
