# Generated by Django 5.2.17 on 2026-10-04 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_canvasrevision_sync_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingcanvas',
            name='operation_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CanvasOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('op_id', models.CharField(max_length=256)),
                ('client_id', models.CharField(max_length=128)),
                ('clock', models.PositiveBigIntegerField()),
                ('operation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='canvas.stagingcanvas')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['canvas', 'sequence'], name='canvas_canv_canvas__b6d48c_idx')],
                'constraints': [models.UniqueConstraint(fields=('canvas', 'sequence'), name='canvas_operation_sequence'), models.UniqueConstraint(fields=('canvas', 'op_id'), name='canvas_operation_op_id')],
            },
        ),
    ]
