# Generated by Django 5.1 on 2026-10-05
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("canvas", "0006_operation_cursor_and_compaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="DialogueMemory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope_key", models.CharField(max_length=180, unique=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("confirmed_facts", models.JSONField(blank=True, default=list)),
                ("working_notes", models.JSONField(blank=True, default=list)),
                ("open_questions", models.JSONField(blank=True, default=list)),
                ("recent_session_summary", models.TextField(blank=True, default="")),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="dialogue_memories", to="core.worldbranch")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dialogue_memories", to="core.worldworkspace")),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [models.Index(fields=["workspace", "branch"], name="canvas_dialo_workspa_8d9f6e_idx")],
            },
        ),
    ]
