# Generated by Django 5.2.17 on 2026-10-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0007_dialoguememory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dialoguememory',
            new_name='canvas_dial_workspa_928b2e_idx',
            old_name='canvas_dialo_workspa_8d9f6e_idx',
        ),
    ]
