# Generated by Django 5.2.18 on 2026-10-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0011_stagingcanvas_purpose_graph'),
        ('core', '0016_workspaceaisecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationproposal',
            name='source_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_relation_proposals', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='relationproposal',
            name='source_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_relations', to='canvas.entityproposal'),
        ),
        migrations.AddConstraint(
            model_name='relationproposal',
            constraint=models.CheckConstraint(condition=models.Q(('source_entity__isnull', False), ('source_proposal__isnull', False), _connector='XOR'), name='relation_proposal_exactly_one_source'),
        ),
    ]
